serviceAccount: "sleepr-cloudbuild@sleepr-452615.iam.gserviceaccount.com"
options:
  logging: CLOUD_LOGGING_ONLY
steps:
  # Auth service
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        ".",
        "-f",
        "apps/auth/Dockerfile",
        "-t",
        "us-east4-docker.pkg.dev/sleepr-452615/auth/production",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "us-east4-docker.pkg.dev/sleepr-452615/auth/production"]
  # Notifications service
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        ".",
        "-f",
        "apps/notifications/Dockerfile",
        "-t",
        "us-east4-docker.pkg.dev/sleepr-452615/notifications/production",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      ["push", "us-east4-docker.pkg.dev/sleepr-452615/notifications/production"]
  # Payments service
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        ".",
        "-f",
        "apps/payments/Dockerfile",
        "-t",
        "us-east4-docker.pkg.dev/sleepr-452615/payments/production",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "us-east4-docker.pkg.dev/sleepr-452615/payments/production"]
  # Reservations service
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        ".",
        "-f",
        "apps/reservations/Dockerfile",
        "-t",
        "us-east4-docker.pkg.dev/sleepr-452615/reservations/production",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      ["push", "us-east4-docker.pkg.dev/sleepr-452615/reservations/production"]
